### PR TITLE
Update e.py

### PR DESCRIPTION
**Pull request by Mrmagicpie**
lmao i added a thing

### CODE REVIEW

**Comment by micah612** [comment]
eeeeeeeeee/10

**Comment by jojoee** [comment]
eee added an eee things

**Comment by jojoee** [comment]
ee eee :rocket: :rocket: :rocket: :rocket:

**Comment by Mrmagicpie** [comment]
lmaoo i didnt expect you to merge it considering me and @Fxcilities don't even know you

**Comment by jojoee** [comment]
that why I love opensource :heart:

**Comment by micah612** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Mrmagicpie** [comment]
i agree

**Pull request merged**
